context:
  name: apache-airflow-providers-git
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_git-${{ version }}.tar.gz
  sha256: 9677a829a2980882d662dedee783da974736767a5485d1304e628963e6e7eaed

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=3.0.0
    - apache-airflow-providers-common-compat >=1.15.0
    - gitpython >=3.1.44

tests:
  - python:
      imports:
        - airflow.providers.git
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-git for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-git/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
